Proyecto.Web/Controllers/GraficoController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.Services.Interfaces;
using Proyecto.Infraestructure.Repository.Interfaces;

namespace Proyecto.Web.Controllers;

public class GraficoController : Controller
{
    private readonly IServiceNFT _serviceNFT;
    private readonly IServiceReportes _serviceReporte;
    private readonly IServiceCliente _serviceCliente;
    private readonly IServiceFactura _serviceFactura;
    private readonly IRepositoryFacturaDetalle _repositoryDetalle;

    public GraficoController(IServiceNFT serviceProducto,
                             IServiceReportes serviceReporte,
                             IServiceCliente serviceCliente,
                             IServiceFactura serviceFactura,
                             IRepositoryFacturaDetalle repositoryFacturaDetalle)
    {
        _serviceNFT = serviceProducto;
        _serviceReporte = serviceReporte;
        _serviceCliente = serviceCliente;
        _serviceFactura = serviceFactura;
        _repositoryDetalle = repositoryFacturaDetalle;
    }
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult GraficoProductos()
    {
        return View();
    }

    public IActionResult GraficoVentas()
    {
        return View();
    }

    public async Task<IActionResult> VentasXCliente(DateTime fechaInicial, DateTime fechaFinal)
    {
        string etiquetas = "";
        string precios = "";
        decimal total = 0M;

        if (string.IsNullOrEmpty(fechaInicial.ToString()))
        {
            ViewBag.Message = $"Fecha Inial Requerida";
            return View("GraficoVentas");
        }

        if (string.IsNullOrEmpty(fechaFinal.ToString()))
        {
            ViewBag.Message = $"fecha Final Requerida";
            return View("GraficoVentas");
        }

        var collectionFacturaEncabezado = await _serviceFactura.FindByReporteXFechas(fechaInicial, fechaFinal);
        var collectionFacturaDetalle = await _repositoryDetalle.ListAsync();
        var collectionNFT = await _serviceNFT.ListAsync();
        var NFTDic = collectionNFT.ToDictionary(c => c.IdNft, c => c.Nombre);
        var collectionClientes = await _serviceCliente.ListAsync();
        var clienteDict = collectionClientes.ToDictionary(c => c.IdCliente, c => $"{c.Nombre} {c.Apellido1} {c.Apellido2}");


        //if (cliente == null)
        //{
        //    ViewBag.Message = $"Cliente Id = {idCliente} No existe";
        //    return View("GraficoVentas");
        //}

        //var lista = await _serviceReporte.BillsByClientIdAsync(idCliente);

        //if (lista.Count == 0)
        //{
        //    ViewBag.Message = $"No hay reportes de ventas para Id = {idCliente}";
        //    return View("GraficoVentas");
        //}
        var clientes = "";
        var cantidad = "";

        foreach (var item in collectionFacturaEncabezado)
        {
            // concatenade 
            foreach (var c in item.ListFacturaDetalle)
            {
                etiquetas += "";
                etiquetas += NFTDic.ContainsKey(c.IdNFT) ? @NFTDic[c.IdNFT] : "";
                etiquetas += ",";
                cantidad += c.Cantidad.ToString("##") + ",";
            }
            etiquetas += "" + item.ListFacturaDetalle.Any() + ",";
            // Has List Any data?
            var sigma = item.ListFacturaDetalle.Any() ? item.ListFacturaDetalle.Sum(p => (p.Cantidad * p.Precio)) : 0;
            total += item.Total;
            precios += sigma.ToString("##") + ",";
            clientes += clienteDict.ContainsKey(item.IdCliente) ? @clienteDict[item.IdCliente] : "";
            clientes += ",";
        }
        etiquetas = etiquetas.Substring(0, etiquetas.Length - 1); // ultima coma
        precios = precios.Substring(0, precios.Length - 1);
        cantidad = precios.Substring(0, cantidad.Length - 1);

        ViewBag.GraphTitle = $"Cliente  {clientes} -  Total de Ventas {total.ToString("###,###.00")} ";
        ViewBag.Etiquetas = etiquetas;
        ViewBag.Valores = precios;
        ViewBag.clientes = clientes;
        ViewBag.cantidadNFT = cantidad;
        return View("GraficoVentas");
    }


    public async Task<IActionResult> InventarioProducto()
    {

        var lista = await _serviceNFT.ListAsync();
        string etiquetas = "";
        string precios = "";
        foreach (var item in lista)
        {
            // Hay que concatenarle comillas 'arduino','xxx', ...
            etiquetas += "" + item.Nombre + ",";
            precios += item.Inventario.ToString() + ",";
        }
        etiquetas = etiquetas.Substring(0, etiquetas.Length - 1); // ultima coma
        precios = precios.Substring(0, precios.Length - 1);


        // toma la lista y le agrega separa por comas (,)

        ViewBag.Etiquetas = etiquetas;
        ViewBag.Valores = precios;
        return View("GraficoProductos");
    }
}

Proyecto.Web/Views/Grafico/GraficoVentas.cshtml
@{
    ViewData["Title"] = "Productos";
}

<div class="container">
    <div class="card">
        <h5 class="card-header">Grafico de Ventas</h5>
        <div class="card-body">

            <form asp-action="VentasXCliente"
                  asp-controller="Grafico">
                <div class="col-auto">
                    <label for="fechaInicial" id="label" class="form-label">Fecha inicial</label>
                    <input type="datetime-local" id="fechaInicial" name="fechaInicial" class="form-control">
                </div>
                <div class="col-auto">
                    <label for="fechaFinal" id="label" class="form-label">Fecha final</label>
                    <input type="datetime-local" id="fechaFinal" name="fechaFinal" class="form-control">
                </div>
                <button class="btn btn-success" type="submit">Consultar</button>
            </form>

            <div class="container">
                <div class="row mt-2 p-2 m-2 ">
                    <div class="col-1 col-sm-6">
                        <canvas id="myChart1" style=""></canvas>
                    </div>
                    <div class="col-1 col-md-6">
                        <canvas id="myChart3" style=""></canvas>
                    </div>
                </div>
                

            </div>

        </div>
    </div>
</div>

@section scripts {


    <script>
        $(document).ready(function () {
            Bar();
            Pie();
            Line();
            Doughnut();
        });

        function Bar() {
            if ("@ViewBag.Valores" == "")
                return;

            // find myChart Div
            const ctx = document.getElementById('myChart1');
            // Get Values
            let yValues = [@ViewBag.Valores];
            // Get Etiquetas
            let etiquetas = "@ViewBag.clientes"
            console.log(etiquetas)

            // Convert to Array
            let etiquetasArray = etiquetas.split(",");

            new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: etiquetasArray,
                    datasets: [{
                        label: '# NFTs',
                        data: yValues,
                        borderWidth: 1,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(255, 159, 64, 0.2)',
                            'rgba(255, 205, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(255, 159, 64, 0.2)',
                            'rgba(255, 205, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(201, 203, 207, 0.2)'
                        ],
                        borderColor: [
                            'rgb(255, 99, 132)',
                            'rgb(255, 159, 64)',
                            'rgb(255, 205, 86)',
                            'rgb(75, 192, 192)',
                            'rgb(54, 162, 235)',
                            'rgb(153, 102, 255)',
                            'rgb(255, 99, 132)',
                            'rgb(255, 159, 64)',
                            'rgb(255, 205, 86)',
                            'rgb(75, 192, 192)',
                            'rgb(54, 162, 235)',
                            'rgb(153, 102, 255)',
                            'rgb(201, 203, 207)'
                        ],
                        borderWidth: 1
                    }]
                }
            });

        }

        function Pie() {
            if ("@ViewBag.Valores" == "")
                return;
            // find myChart Div
            const ctx = document.getElementById('myChart3');
            // Get Values
            let yValues = [@ViewBag.cantidadNFT];
            // Get Etiquetas
            let etiquetas = "@ViewBag.clientes"
            // Convert to Array
            let etiquetasArray = etiquetas.split(",");

            new Chart(ctx, {
                type: 'pie', //
                data: {
                    labels: etiquetasArray,
                    datasets: [{
                        label: '# Total',
                        data: yValues,
                        borderWidth: 1
                    }]
                },
            });
        }




    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}