Proyecto.Web/Controllers/TarjetaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.DTOs;
using Proyecto.Application.Services.Implementations;
using Proyecto.Application.Services.Interfaces;
using X.PagedList;

namespace Proyecto.Web.Controllers;

[Authorize(Roles = "Admin,Procesos")]
public class TarjetaController : Controller
{
    private readonly IServicesTarjeta _serviceTarjeta;

    public TarjetaController(IServicesTarjeta serviceTarjeta)
    {
        _serviceTarjeta = serviceTarjeta;
    }

    [HttpGet]
    public async Task<IActionResult> Index(int? page)
    {
        var collection = await _serviceTarjeta.ListAsync();
        return View(collection.ToPagedList(page ?? 1, 5));
    }

    public async Task<IActionResult> List(string descripcion)
    {
        if (string.IsNullOrEmpty(descripcion))
            return RedirectToAction("Index");

        var collection = await _serviceTarjeta.FindByDescriptionAsync(descripcion);
        return View("index", collection.ToPagedList(1, 10));
    }

    // GET: BodegaController/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: BodegaController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(TarjetaDTO dto)
    {

        if (!ModelState.IsValid)
        {
            // Lee del ModelState todos los errores que
            // vienen para el lado del server
            string errors = string.Join("; ", ModelState.Values
                               .SelectMany(x => x.Errors)
                               .Select(x => x.ErrorMessage));
            return BadRequest(errors);
        }

        var Tarejetas = await _serviceTarjeta.FindByIdAsync(dto.IdTarjeta);

        if (Tarejetas != null)
        {
            ViewData["Mensaje"] = "Ya se encuentra registrado esta Tarjeta!";
            return View("Create");
        }

        await _serviceTarjeta.AddAsync(dto);


        return RedirectToAction("Index");

    }


    // GET: BodegaController/Details/5
    public async Task<IActionResult> Details(int id)
    {
        var @object = await _serviceTarjeta.FindByIdAsync(id);

        return PartialView(@object);
    }

    // GET: BodegaController/Edit/5
    public async Task<IActionResult> Edit(int id)
    {
        var @object = await _serviceTarjeta.FindByIdAsync(id);

        return View(@object);
    }

    // POST: BodegaController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, TarjetaDTO dto)
    {
        var tarjetas = await _serviceTarjeta.FindByDescriptionAsync(dto.DescripcionTarjeta);

        if (tarjetas.Count() > 0)
        {
            ViewData["Mensaje"] = "Ya se encuentra registrado esta Tarjeta!";
            return View("Edit");
        }

        await _serviceTarjeta.UpdateAsync(id, dto);

        return RedirectToAction("Index");

    }

    // GET: BodegaController/Delete/5
    public async Task<IActionResult> Delete(int id)
    {
        var @object = await _serviceTarjeta.FindByIdAsync(id);

        return View(@object);

    }

    // POST: BodegaController/Delete/5
    [HttpPost]
    public async Task<IActionResult> DeleteConfirm(int id)
    {
        await _serviceTarjeta.DeleteAsync(id);

        return RedirectToAction("Index");
    }
}

Proyecto.Web/Views/Tarjeta/Create.cshtml
@model Proyecto.Application.DTOs.TarjetaDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Tarjeta</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="crear">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdTarjeta" class="control-label"></label>
                <input asp-for="IdTarjeta" class="form-control" />
                <span asp-validation-for="IdTarjeta" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <label asp-for="DescripcionTarjeta" class="control-label"></label>
                <input asp-for="DescripcionTarjeta" class="form-control" />
                <span asp-validation-for="DescripcionTarjeta" class="text-danger"></span>
            </div>
            <div class="form-group form-check mt-2">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                |
                <a asp-action="Index" class="btn btn-success">Regresar</a>

            </div>
        </form>
    </div>
</div>

@if (ViewData["Mensaje"] != null)
{
    String mensaje = ViewData["Mensaje"] != null ? ViewData["Mensaje"]!.ToString()! : " ";
    <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
        <i class="bi bi-exclamation-triangle-fill"></i>
        @mensaje
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<br />
<div id="contenedor"></div>
<div id="loader" class="xxxx"></div>
<br />

@section Scripts {
    <script type="text/javascript">

        document.getElementById("crear").addEventListener("submit", function (event) {
        
            event.preventDefault();
            event.stopPropagation();
     
            if (event.target.checkValidity()) {
         
                var idTarjeta = document.getElementById("IdTarjeta").value.trim();
                var descripcionTarjeta = document.getElementById("DescripcionTarjeta").value.trim();

                if (idTarjeta !== "" && descripcionTarjeta !== "") {
         
                    Swal.fire({
                        title: '¿Estás seguro?',
                        text: '¿Deseas guardar los cambios en esta Tarjeta?',
                        icon: 'question',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Sí, guardar cambios',
                        cancelButtonText: 'Cancelar'

                    }).then((result) => {
                  
                        if (result.isConfirmed) {
                            onBegin();
                            setTimeout(function () {
                                document.getElementById('crear').submit();
                            }, 1000);
                        }
                    });
                }
            }
        });

        function onBegin() {
            console.log("onBegin")
            document.getElementById("loader").className = "loading";
        }

    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto.Web/Views/Tarjeta/Details.cshtml
@model Proyecto.Application.DTOs.TarjetaDTO

<style>
    .custom-dl dt {
        text-align: left;
    }
</style>

<div class="container">
    <hr />
    <dl class="row custom-dl">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.IdTarjeta)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.IdTarjeta)
        </dd>
        <hr />
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.DescripcionTarjeta)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.DescripcionTarjeta)
        </dd>
        <hr />
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd class="col-sm-8">
            @{
                string estado = Model.Estado ? "Activo" : "Inactivo";
                @Html.Raw(estado)
                ;
            }
        </dd>
    </dl>
</div>

Proyecto.Web/Views/Tarjeta/Edit.cshtml
@model Proyecto.Application.DTOs.TarjetaDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="edit">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdTarjeta" class="control-label"></label>
                <input asp-for="IdTarjeta" class="form-control" />
                <span asp-validation-for="IdTarjeta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionTarjeta" class="control-label"></label>
                <input asp-for="DescripcionTarjeta" class="form-control" />
                <span asp-validation-for="DescripcionTarjeta" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                |
                <a asp-action="Index" class="btn btn-success">Regresar</a>

            </div>
        </form>
    </div>
</div>


<br />
@if (ViewData["Mensaje"] != null)
{
    String mensaje = ViewData["Mensaje"] != null ? ViewData["Mensaje"]!.ToString()! : " ";
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-triangle-fill"></i>
        @mensaje
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<br />
<div id="contenedor"></div>
<div id="loader" class="xxxx"></div>
<br />

@section Scripts {
    <script type="text/javascript">

        document.getElementById("crear").addEventListener("submit", function (event) {

            event.preventDefault();
            event.stopPropagation();

            if (event.target.checkValidity()) {

                var idTarjeta = document.getElementById("IdTarjeta").value.trim();
                var descripcionTarjeta = document.getElementById("DescripcionTarjeta").value.trim();

                if (idTarjeta !== "" && descripcionTarjeta !== "") {

                    Swal.fire({
                        title: '¿Estás seguro?',
                        text: '¿Deseas guardar los cambios en esta Tarjeta?',
                        icon: 'question',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Sí, guardar cambios',
                        cancelButtonText: 'Cancelar'

                    }).then((result) => {

                        if (result.isConfirmed) {
                            onBegin();
                            setTimeout(function () {
                                document.getElementById('crear').submit();
                            }, 1000);
                        }
                    });
                }
            }
        });

        function onBegin() {
            console.log("onBegin")
            document.getElementById("loader").className = "loading";
        }

    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto.Web/Views/Tarjeta/Index.cshtml
@model IEnumerable<Proyecto.Application.DTOs.TarjetaDTO>
@using X.PagedList
@using X.PagedList.Mvc.Core

@{
    ViewData["Title"] = "Index";
}

<h1 class="mb-5">Mantenimiento Tarjetas</h1>

<form asp-controller="Tarjeta" asp-action="List" method="get">
    <div class="d-flex justify-content-between">
        <p>
            <a asp-action="Create" class="btn btn-primary">Crear <spam class="bi-plus-circle-fill"></spam></a>
        </p>
        <div class="d-flex flex-row-reverse">
            <div class="px-2">
                <input type="submit" class="btn btn-primary" value="Consultar" />
            </div>
            <div>
                <input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Descripción de la tarjeta" />
            </div>
        </div>
    </div>
</form>

<div class="table-responsive">
    <table class="table table-striped table-hover table-responsive-md table-sm mt-3" style="border-radius: 6px; overflow: hidden; font-size:medium">
        <thead style="background-color: black; color: #fff; cursor:pointer ; height: 50px;text-align: left; vertical-align: middle;">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdTarjeta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DescripcionTarjeta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="row_@item.IdTarjeta">
                    <td>
                        @Html.DisplayFor(modelItem => item.IdTarjeta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescripcionTarjeta)
                    </td>
                    <td>
                        @{
                            string estado = item.Estado ? "Activo" : "Inactivo";
                            @Html.Raw(estado)
                            ;

                        }
                    </td>
                    <td class="d-flex justify-content-center flex-lg-wrap gap-1">
                        @Html.ActionLink(" Editar", "Edit", new { id = item.IdTarjeta }, new { @class = "btn btn-success    bi-eye-fill  " }) |
                        <a data-ajax="true" class="btn btn-secondary  bi-info-circle"
                           data-ajax-complete="onComplete"
                           data-ajax-mode="replace"
                           href='@Url.Action("Details", "Tarjeta", new { id  = item.IdTarjeta })'>
                            Detalles
                        </a>
                        |
                        <button type="button" class="btn btn-danger bi bi-trash" onclick="deleteItem(@item.IdTarjeta, '@item.DescripcionTarjeta')">Eliminar</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@Html.PagedListPager((IPagedList)Model, page =>
                        Url.Action("Index", new { page }), new PagedListRenderOptions
                    {
                        Display = PagedListDisplayMode.Always,
                        MaximumPageNumbersToDisplay = 5,
                        LiElementClasses = new String[] { "page-item" },
                        PageClasses = new String[] { "page-link" }
                    })

@section Scripts {
    <script>

        function onComplete(data) {
            Swal.fire({
                title: 'Detalles ',
                html: data.responseText,
                showDenyButton: false,
                showOkButton: false,
                showCancelButton: false,
            })
        };

        function deleteItem(id, name) {
            Swal.fire({
                title: '¿Eliminar Tarjeta?',
                html: '¿Estás seguro de que quieres eliminar la Tarjeta <strong>' + name + '</strong>?<br>Esta acción no se puede deshacer.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Sí, eliminarlo',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    const myRequest = "/Tarjeta/DeleteConfirm?id=" + id;
                    fetch(myRequest, {
                        method: 'POST',
                    }).then((response) => response.text())
                        .then((text) => {
                            console.log(text);
                            // Eliminar la fila correspondiente de la tabla
                            document.getElementById('row_' + id).remove();
                            Swal.fire('¡Eliminado!', '', 'success');
                        });
                }
            });
        }

    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}