Proyecto.Web/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.DTOs;
using Proyecto.Application.Services.Implementations;
using Proyecto.Application.Services.Interfaces;
using Proyecto.Infraestructure.Models;
using X.PagedList;

namespace Proyecto.Web.Controllers;

[Authorize(Roles = "Admin,Procesos")]
public class ClienteController : Controller
{
    private readonly IServiceCliente _serviceCliente;
    private readonly IServicesPais _servicePais;

    public ClienteController(IServiceCliente serviceCliente, IServicesPais servicePais)
    {
        _serviceCliente = serviceCliente;
        _servicePais = servicePais;
    }

    [HttpGet]
    public async Task<IActionResult> Index(int? page)
    {
        var collection = await _serviceCliente.ListAsync();
        return View(collection.ToPagedList(page ?? 1, 5));
    }

    public async Task<IActionResult> List(string nombre)
    {
        if (string.IsNullOrEmpty(nombre))
            return RedirectToAction("Index");

        var collection = await _serviceCliente.FindByNameAsync(nombre);
        return View("index", collection.ToPagedList(1, 10));
    }

    public async Task<IActionResult> Create()
    {
        ViewBag.ListPais = await _servicePais.ListAsync();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ClienteDTO dto)
    {
        dto.IdCliente = Guid.NewGuid();
        
        if (!ModelState.IsValid)
        {
            // Lee del ModelState todos los errores que
            // vienen para el lado del server
            string errors = string.Join("; ", ModelState.Values
                               .SelectMany(x => x.Errors)
                               .Select(x => x.ErrorMessage));
            return BadRequest(errors);
        }

        await _serviceCliente.AddAsync(dto);
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Details(Guid id)
    {
        var @object = await _serviceCliente.FindByIdAsync(id);
        return PartialView(@object);
    }

    public async Task<IActionResult> Delete(Guid id)
    {
        var @object = await _serviceCliente.FindByIdAsync(id);

        return View(@object);

    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirm(Guid id)
    {
        await _serviceCliente.DeleteAsync(id);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Edit(Guid id)
    {
        var @object = await _serviceCliente.FindByIdAsync(id);
        ViewBag.ListPais = await _servicePais.ListAsync();
        return View(@object);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, ClienteDTO dto)
    {
        await _serviceCliente.UpdateAsync(id, dto);
        return RedirectToAction("Index");

    }

    public IActionResult GetClienteByName(string filtro)
    {

        var collections = _serviceCliente.FindByNameAsync(filtro).GetAwaiter().GetResult();

        return Json(collections);
    } 
}

Proyecto.Web/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.DTOs;
using Proyecto.Application.Services.Implementations;
using Proyecto.Application.Services.Interfaces;
using System.Text.Json;
using X.PagedList;

namespace Proyecto.Web.Controllers;

[Authorize(Roles = "Admin,Procesos")]
public class FacturaController : Controller
{
    private readonly IServiceNFT _serviceNFT;
    private readonly IServicesTarjeta _serviceTarjeta;
    private readonly IServiceFactura _serviceFactura;
    private readonly IServiceCliente _serviceCliente;

    public FacturaController(IServiceNFT serviceNFT,
                         IServicesTarjeta servicoTarjeta,
                         IServiceFactura serviceFactura,
                         IServiceCliente serviceCliente)
    {
        _serviceNFT = serviceNFT;
        _serviceTarjeta = servicoTarjeta;
        _serviceFactura = serviceFactura;
        _serviceCliente = serviceCliente;
    }

    public async Task<IActionResult> Index()
    {
        var nextReceiptNumber = await _serviceFactura.GetNextReceiptNumber();
        ViewBag.CurrentReceipt = nextReceiptNumber;
        var collection = await _serviceTarjeta.ListAsync();
        ViewBag.ListTarjeta = collection;

        // Clear CarShopping
        TempData["CartShopping"] = null;
        TempData.Keep();

        return View();
    }

    public async Task<IActionResult> AnularFacturaIndex(int? page)
    {
        ViewBag.clientes = await _serviceCliente.ListAsync();
        var collection = await _serviceFactura.ListAsync();
        return View(collection.ToPagedList(page ?? 1, 5));
    }

    public async Task<IActionResult> List(string nombre)
    {
        if (string.IsNullOrEmpty(nombre))
            return RedirectToAction("AnularFacturaIndex");

        ViewBag.clientes = await _serviceCliente.ListAsync();
        var collection = await _serviceFactura.FindByClientNameAsync(nombre);
        return View("AnularFacturaIndex", collection.ToPagedList(1, 10));
    }


    //public async Task<IActionResult> CambiarEstado(int id)
    //{
    //    var @object = await _serviceFactura.FindByIdAsync(id);
    //    return View(@object);

    //}

    [HttpPost]
    //[ValidateAntiForgeryToken]
    public async Task<IActionResult> CambiarEstado(int id)
    {
        await _serviceFactura.CancelAsync(id);
        return RedirectToAction("AnularFacturaIndex");

    }

    public async Task<IActionResult> AddProduct(Guid id, int cantidad)
    {
        FacturaDetalleDTO facturaDetalleDTO = new FacturaDetalleDTO();
        List<FacturaDetalleDTO> lista = new List<FacturaDetalleDTO>();
        string json = "";

        var producto = await _serviceNFT.FindByIdAsync(id);

        // Stock ??
        if (cantidad > producto.Inventario)
        {
            return BadRequest("No hay inventario suficiente!");
        }


        facturaDetalleDTO.DescripcionProducto = producto.Nombre;
        facturaDetalleDTO.Cantidad = cantidad;
        facturaDetalleDTO.Precio = producto.Precio;
        facturaDetalleDTO.IdNFT = id;
        facturaDetalleDTO.TotalLinea = (facturaDetalleDTO.Precio * facturaDetalleDTO.Cantidad);
        if (TempData["CartShopping"] == null)
        {
            lista.Add(facturaDetalleDTO);
            // Reenumerate 
            int idx = 1;
            lista.ForEach(p => p.Secuencia = idx++);
            json = JsonSerializer.Serialize(lista);
            TempData["CartShopping"] = json;
        }
        else
        {
            json = (string)TempData["CartShopping"]!;
            lista = JsonSerializer.Deserialize<List<FacturaDetalleDTO>>(json!)!;
            lista.Add(facturaDetalleDTO);
            // Reenumerate 
            int idx = 1;
            lista.ForEach(p => p.Secuencia = idx++);
            json = JsonSerializer.Serialize(lista);
            TempData["CartShopping"] = json;
        }

        TempData.Keep();
        return PartialView("_DetailFactura", lista);
    }

    public IActionResult GetDetailFactura()
    {
        List<FacturaDetalleDTO> lista = new List<FacturaDetalleDTO>();
        string json = "";
        json = (string)TempData["CartShopping"]!;
        lista = JsonSerializer.Deserialize<List<FacturaDetalleDTO>>(json!)!;
        // Reenumerate 
        int idx = 1;
        lista.ForEach(p => p.Secuencia = idx++);
        json = JsonSerializer.Serialize(lista);
        TempData["CartShopping"] = json;
        TempData.Keep();

        return PartialView("_DetailFactura", lista);
    }

    public IActionResult DeleteProduct(int id)
    {
        FacturaDetalleDTO facturaDetalleDTO = new FacturaDetalleDTO();
        List<FacturaDetalleDTO> lista = new List<FacturaDetalleDTO>();
        string json = "";

        if (TempData["CartShopping"] != null)
        {
            json = (string)TempData["CartShopping"]!;
            lista = JsonSerializer.Deserialize<List<FacturaDetalleDTO>>(json!)!;
            // Remove from list by Index
            int idx = lista.FindIndex(p => p.Secuencia == id);
            lista.RemoveAt(idx);
            json = JsonSerializer.Serialize(lista);
            TempData["CartShopping"] = json;
        }

        TempData.Keep();

        // return Content("Ok");
        return PartialView("_DetailFactura", lista);

    }


    public async Task<IActionResult> Create(FacturaDTO facturaEncabezadoDTO)
    {
        string json;
        try
        {

            // IdClient exist?
            var cliente = await _serviceCliente.FindByIdAsync(facturaEncabezadoDTO.IdCliente);
            if (cliente == null)
            {
                // Keep Cache data
                TempData.Keep();
                return BadRequest("Cliente No Existe!");
            }


            // TODO: Validate! 
            if (!ModelState.IsValid)
            {

            }

            json = (string)TempData["CartShopping"]!;

            if (string.IsNullOrEmpty(json))
            {
                return BadRequest("No hay datos por facturar");
            }

            var lista = JsonSerializer.Deserialize<List<FacturaDetalleDTO>>(json!)!;

            if (lista.Count == 0 || lista == null)
            {
                return BadRequest("No hay datos por facturar");
            }

            //Mismo numero de factura para el detalle FK
            lista.ForEach(p => p.IdFactura = facturaEncabezadoDTO.IdFactura);
            facturaEncabezadoDTO.ListFacturaDetalle = lista;

            await _serviceFactura.AddAsync(facturaEncabezadoDTO);


            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            // Keep Cache data
            TempData.Keep();
            return BadRequest(ex.Message);
        }
    }


}

Proyecto.Web/Controllers/NFTController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.DTOs;
using Proyecto.Application.Services.Interfaces;
using X.PagedList;

namespace Proyecto.Web.Controllers;

[Authorize(Roles = "Admin,Procesos")]
public class NFTController : Controller
{
    private readonly IServiceNFT _serviceNFT;

    public NFTController(IServiceNFT serviceNFT)
    {
        _serviceNFT = serviceNFT;
    }

    [HttpGet]
    public async Task<IActionResult> Index(int? page)
    {
        var collection = await _serviceNFT.ListAsync();
        return View(collection.ToPagedList(page ?? 1, 5));
    }

    public async Task<IActionResult> List(string nombre)
    {
        if (string.IsNullOrEmpty(nombre))
            return RedirectToAction("Index");

        var collection = await _serviceNFT.FindByNameAsync(nombre);
        return View("index", collection.ToPagedList(1, 10));
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(NFTDTO dto, IFormFile imageFile)
    {
        dto.IdNft = Guid.NewGuid();

        MemoryStream target = new MemoryStream();

        // Cuando es Insert Image viene en null porque se pasa diferente
        if (dto.Imagen == null)
        {
            if (imageFile != null)
            {
                imageFile.OpenReadStream().CopyTo(target);

                dto.Imagen = target.ToArray();
                ModelState.Remove("Imagen");
            }
        }

        if (!ModelState.IsValid)
        {
            // Lee del ModelState todos los errores que
            // vienen para el lado del server
            string errors = string.Join("; ", ModelState.Values
                               .SelectMany(x => x.Errors)
                               .Select(x => x.ErrorMessage));
            return BadRequest(errors);
        }

        await _serviceNFT.AddAsync(dto);
        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Details(Guid id)
    {
        var @object = await _serviceNFT.FindByIdAsync(id);
        return View(@object);
    }

    public async Task<IActionResult> Delete(Guid id)
    {
        var @object = await _serviceNFT.FindByIdAsync(id);

        return View(@object);

    }

    [HttpPost]
    public async Task<IActionResult> DeleteConfirm(Guid id)
    {
        await _serviceNFT.DeleteAsync(id);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> Edit(Guid id)
    {
        var @object = await _serviceNFT.FindByIdAsync(id);
        return View(@object);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, NFTDTO dto, IFormFile imageFile)
    {
        // Verificar si se ha seleccionado un nuevo archivo de imagen
        if (imageFile != null && imageFile.Length > 0)
        {
            // Si se ha seleccionado un archivo de imagen, actualizar la imagen en el DTO
            using (var memoryStream = new MemoryStream())
            {
                await imageFile.CopyToAsync(memoryStream);
                dto.Imagen = memoryStream.ToArray();
            }
        }
        else
        {
            NFTDTO nft = await _serviceNFT.FindByIdAsync(id);
            dto.Imagen = nft.Imagen;
        }

        // Realizar la actualización del NFT con los datos proporcionados
        await _serviceNFT.UpdateAsync(id, dto);
        return RedirectToAction("Index");
    }

    public async Task<IActionResult> GetProductoByName(string filtro)
    {

        var collection = await _serviceNFT.FindByDescriptionAsync(filtro);
        return Json(collection);

    }
}

Proyecto.Web/Controllers/PaisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.DTOs;
using Proyecto.Application.Services.Implementations;
using Proyecto.Application.Services.Interfaces;
using X.PagedList;

namespace Proyecto.Web.Controllers;

[Authorize(Roles = "Admin,Procesos")]
public class PaisController : Controller
{
    private readonly IServicesPais _servicePais;

    public PaisController(IServicesPais servicePais)
    {
        _servicePais = servicePais;
    }

    [HttpGet]
    public async Task<IActionResult> Index(int? page)
    {
        var collection = await _servicePais.ListAsync();
        return View(collection.ToPagedList(page ?? 1, 5));
    }

    public async Task<IActionResult> List(string descripcion)
    {
        if (string.IsNullOrEmpty(descripcion))
            return RedirectToAction("Index");

        var collection = await _servicePais.FindByDescriptionAsync(descripcion);
        return View("index", collection.ToPagedList(1, 10));
    }

    // GET: PaisController/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: PaisController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(PaisDTO dto)
    {
        if (!ModelState.IsValid)
        {
            // Lee del ModelState todos los errores que
            // vienen para el lado del server
            string errors = string.Join("; ", ModelState.Values
                               .SelectMany(x => x.Errors)
                               .Select(x => x.ErrorMessage));
            return BadRequest(errors);
        }
        var paises = await _servicePais.FindByIdAsync(dto.IdPais);

        if (paises != null)
        {
            ViewData["Mensaje"] = "Ya se encuentra registrado este Pais!";
            return View("Create");
        }
        //no estra al if se agrega normal 
        await _servicePais.AddAsync(dto);


        return RedirectToAction("Index");

    }

    public async Task<IActionResult> Details(string id)
    {
        var @object = await _servicePais.FindByIdAsync(id);

        return PartialView(@object);
    }

    // GET: PaisController/Edit/5
    public async Task<IActionResult> Edit(string id)
    {
        var @object = await _servicePais.FindByIdAsync(id);

        return View(@object);
    }

    // POST: PaisController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(string id, PaisDTO dto)
    {
        var paises = await _servicePais.FindByDescriptionAsync(dto.Descripcion);

        if (paises.Count() > 0)
        {
            ViewData["Mensaje"] = "Ya se encuentra registrado este Pais!";
            return View("Edit");
        }

        await _servicePais.UpdateAsync(id, dto);

        return RedirectToAction("Index");

    }

    // GET: PaisController/Delete/5
    public async Task<IActionResult> Delete(string id)
    {
        var @object = await _servicePais.FindByIdAsync(id);

        return View(@object);

    }

    // POST: PaisController/Delete/5
    [HttpPost]
    public async Task<IActionResult> DeleteConfirm(string id)
    {
        await _servicePais.DeleteAsync(id);

        return RedirectToAction("Index");
    }

}

Proyecto.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto.Web.styles.css" asp-append-version="true" />
    <!-- Toast-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <!-- SweetAlert-->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.4/dist/sweetalert2.min.css" rel="stylesheet">
    <!--AutoComplete https://www.cssscript.com/demo/bootstrap-5-autocomplete/ -->
    <link href="~/css/autocompleteBS.css" rel="stylesheet">
    <!-- Add Bootstrap Icons Support! -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!--JQuery UI CSS-->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
       @await Html.PartialAsync("_Menu")
       <br/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Proyecto.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Ajax unobtrusive-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js" integrity="sha512-f04GBpoqEZhbyjlRTuXeg8FIHDb+xfCJ0LVdqiN1fEl5B3jz3Z0SPe9IxDumOVdTeeXmKMcMJhb26VuGf1Laqw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Toast-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <!-- SweetAlert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.4/dist/sweetalert2.all.min.js"></script>
    <!--AutoComplete  https://www.cssscript.com/demo/bootstrap-5-autocomplete/  -->
    <script src="~/js/autocompleteBS.js" asp-append-version="true"></script>
    <!-- JQuery UI Autocomplete -->
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <!-- Charts -->
    <script src=" https://cdn.jsdelivr.net/npm/chart.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Proyecto.Web/Views/Shared/_Menu.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NFT SHOP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                @if (User.IsInRole("Admin") || User.IsInRole("Procesos"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="mantenimientosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Mantenimientos
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="mantenimientosDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("Index","Pais")">Pais</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index","Cliente" )">Cliente</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index","NFT")">NFT</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index","Tarjeta")">Tarjeta</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="procesosDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Procesos
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="procesosDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Factura")">Facturación</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("AnularFacturaIndex", "Factura" )">Anular Factura</a></li>
                        </ul>
                    </li>
                }
                @if (User.IsInRole("Admin") || User.IsInRole("Reportes"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="reportesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Reportes
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="reportesDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("ClienteReportByNFT", "Reportes" )">Dueño NFT </a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ReporteClientes", "Reportes")">Lista de clientes</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ReporteNFTs", "Reportes")">Lista de NFTs</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="@Url.Action("GraficoVentas", "Grafico")">Grafico de ventas</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ReporteVentasByFecha", "Reportes")">Lista de ventas por fecha</a></li>
                        </ul>
                    </li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="seguridadDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Seguridad
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="seguridadDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Usuario")">Usuario</a></li>
                        </ul>
                    </li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="seguridadDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Calificación
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="seguridadDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("Index", "Calificacion")">Calificación</a></li>
                        </ul>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Login" asp-action="LogOff">Salir</a>

                </li>

            </ul>

        </div>
        <div class="d-flex align-items-center justify-content-center" style="text-align:center">
            <a class="align-self-center" style="color:white">@User.Identity!.Name</a>
            <img class="rounded-circle mx-2" src="/Images/user.png" alt="@User.Identity!.Name" width="35px" height="35px" />
        </div>
    </div>
</nav>