Proyecto.Web/Controllers/ReportesController.cs
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;
using Proyecto.Application.DTOs;
using Proyecto.Application.Services.Implementations;
using Proyecto.Application.Services.Interfaces;
using Proyecto.Infraestructure.Models;
using Proyecto.Infraestructure.Repository.Implementations;
using Proyecto.Infraestructure.Repository.Interfaces;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Tokens;


namespace Proyecto.Web.Controllers;

[Authorize(Roles = "Admin,Reportes")]
public class ReportesController : Controller
{
    private readonly IServiceReportes _servicioReporte;
    private readonly IServiceNFT _serviceNFT;
    private readonly IServiceFactura _serviceFactura;
    private readonly IServiceCliente _serviceCliente;
    private readonly IServiceMovimientosCompras _serviceMovimientosCompras;
    public ReportesController(IServiceReportes servicioReporte,
                                               IServiceNFT serviceNFT,
                                               IServiceFactura serviceFactura, 
                                               IServiceCliente serviceCliente,
                                               IServiceMovimientosCompras serviceMovimientosCompras)
    {
        _servicioReporte = servicioReporte;
        _serviceNFT = serviceNFT;
        _serviceFactura = serviceFactura;
        _serviceCliente = serviceCliente;
        _serviceMovimientosCompras = serviceMovimientosCompras;

    }
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult ReporteClientes()
    {
        return View();
    }

    public IActionResult ReporteNFTs()
    {
        return View();
    }

    public IActionResult ClienteReportByNFT()
    {
        return View();
    }

    public IActionResult ReporteVentasByFecha()
    {
        return View();
    }

    public async Task<IActionResult> ClienteReportByNFTResult(string nombreNFT)
    {
        var collection = await _serviceNFT.FindByNameXReporteAsync(nombreNFT);
        ClienteDTO cliente = new ClienteDTO();
        if (collection.Any())
        {
            var nftId = collection.First().IdNft;
            var collectionMovimientos = await _serviceMovimientosCompras.FindByIdNFT(nftId);
            //validamos si tiene movimientos
            if (collectionMovimientos.Any())
            {
                // preguntamos cual es el dueño para despues cargar los datos de ese cliente
                var clienteMovimientos = ((IEnumerable<MovimientosComprasDTO>)collectionMovimientos).ToList();
                var clienteDict = clienteMovimientos.ToDictionary(c => c.Estado, c => c.ClienteId);

                if (clienteDict.ContainsKey(true))
                {
                    Guid id = clienteDict[true];
                    //cliente
                    cliente = await _serviceCliente.FindByIdAsync(id);
                }
                //pasamos la info del nft a la vista para usarla con el cliente
                ViewBag.nft = collection;
            }
            else
            {
                // Maneja el caso en que la colección esté vacía...
                return BadRequest("No hay registros!");
            }
           
        }
        else
        {
            // Maneja el caso en que la colección esté vacía...
            return BadRequest("No existe ese NFT!");
        }

        return PartialView("details", cliente);
    }

    [HttpPost]
    [RequireAntiforgeryToken]
    public async Task<FileResult> ClientesReportPDF()
    {
        byte[] bytes = await _servicioReporte.ClientesReportPDF();
        return File(bytes, "text/plain", "clientes.pdf");
    }

    [HttpPost]
    [RequireAntiforgeryToken]
    public async Task<FileResult> NFTsReportPDF()
    {
        byte[] bytes = await _servicioReporte.NFTsReportPDF();
        return File(bytes, "text/plain", "NFTs.pdf");
    }

    [HttpPost]
    [RequireAntiforgeryToken]
    public async Task<IActionResult> VentasReportByFechaPDF(DateTime fechaInicial, DateTime fechaFinal)
    {
        if(fechaInicial.ToString() == null)
        {
            return BadRequest("Tiene que seleccionar la Fecha Inicial");
        }

        if (fechaFinal.ToString() == null)
        {
            return BadRequest("Tiene que seleccionar la Fecha Inicial");
        }
        byte[] bytes = await _servicioReporte.VentaReporteByFechas(fechaInicial, fechaFinal);
        return File(bytes, "text/plain", "ventas.pdf");
    } 
}

Proyecto.Web/Views/Reportes/ClienteReportByNFT.cshtml
@model IEnumerable<Proyecto.Application.DTOs.ClienteDTO>

@{
    ViewData["Title"] = "ClienteReportByNFT";
}

@using X.PagedList
@using X.PagedList.Mvc.Core



<form asp-controller="Reportes" asp-action="ClienteReportByNFTResult" method="get"
      data-ajax="true" asp-antiforgery="true"
      data-ajax-method="POST"
      data-ajax-begin="onBegin"
      data-ajax-failure="onFailure"
      data-ajax-success="onSuccess"
      data-ajax-complete="onComplete">
    <div class="d-flex justify-content-between">
        <div class="d-flex flex-row-reverse">
            <div class="px-2">
                <input type="submit" class="btn btn-primary" value="Consultar" />
            </div>
            <div>
                <input type="text" name="nombreNFT" id="nombreNFT" class="form-control" placeholder="Nombre del NFT" />
            </div>
        </div>
    </div>
</form>

<br />
<div id="contenedor"></div>
<div id="loader" class="xxxx"></div>
<br />


@section scripts {


    <script>
        function onBegin() {
            console.log("onBegin")
            document.getElementById("loader").className = "loading";

        }

        function onFailure(data) {
            console.log(data)
            document.getElementById("loader").className = "";


            toastr.options.closeDuration = 2000;
            toastr.options.closeEasing = 'swing';
            toastr.options.progressBar = true;
            toastr.error('Error !' + data.responseText)

        }

        function onSuccess(data) {
            console.log("onSuccess")
            document.getElementById("loader").className = "";

        }

        function onComplete(data) {

            console.log("onComplete")
            let div = document.getElementById("contenedor")
            div.innerHTML = data.responseText
            document.getElementById("loader").className = "";
        }
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto.Web/Views/Reportes/ReporteClientes.cshtml
@{
    ViewData["Title"] = "Clientes PDF";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            Reporte de Clientes
        </div>
        <div class="card-body">
            <form asp-action="ClientesReportPDF"
                  asp-controller="Reportes"
                  asp-antiforgery="true"
                  method="post"
                  asp-antiforgery="true">

                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Descargar lista de clientes PDF</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

Proyecto.Web/Views/Reportes/ReporteNFTs.cshtml
@{
    ViewData["Title"] = "NFTs PDF";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            Reporte de NFTs
        </div>
        <div class="card-body">
            <form asp-action="NFTsReportPDF"
                  asp-controller="Reportes"
                  asp-antiforgery="true"
                  method="post"
                  asp-antiforgery="true">

                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Descargar lista de NFTs PDF</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

Proyecto.Web/Views/Reportes/ReporteVentasByFecha.cshtml
@{
    ViewData["Title"] = "VentasByFecha PDF";
}

<div class="container">
    <div class="card">
        <div class="card-header">
            Reporte ventas por fecha
        </div>
        <div class="card-body">
            <form asp-action="VentasReportByFechaPDF"
                  asp-controller="Reportes"
                  asp-antiforgery="true"
                  method="post"
                  asp-antiforgery="true" onsubmit="return validateForm()">

                <div class="row g-3 align-items-end flex-lg-wrap">
                    <div class="col-auto">
                        <label for="fechaInicial" id="label" class="form-label">Fecha inicial</label>
                        <input type="datetime-local" id="fechaInicial" name="fechaInicial" class="form-control">
                    </div>
                    <div class="col-auto">
                        <label for="fechaFinal" id="label" class="form-label">Fecha final</label>
                        <input type="datetime-local" id="fechaFinal" name="fechaFinal" class="form-control">
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-success">Consultar</button>
                    </div>
                </div>
            </form>
            <br />
            @if (ViewBag.Message != null)
            {
                <div class="alert alert-danger" id="Message" role="alert">
                    @ViewBag.Message
                </div>
            }

        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">

        function validateForm() {
            let fechaInicial = document.getElementById("fechaInicial");
            let fechaFinal = document.getElementById("fechaFinal");

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-center",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

            console.log(fechaInicial.value)
            console.log(fechaFinal.value)

            if (fechaInicial.value === "") {
                toastr["error"]("La fecha inicial es requerida!", "Atención")
                return false;
            }

            if (fechaFinal.value === "") {
                toastr["error"]("La fecha final es requerida!", "Atención")
                return false;
            }

            return true;
        }

        function clearMessage() {
            let divMessage = document.getElementById("Message");
            // timeout to clear message
            if (divMessage != null)
                setTimeout(() => { divMessage.remove(); }, 3000);
            console.log("bye");
        }

        clearMessage();

    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Proyecto.Web/Views/Reportes/details.cshtml
@model Proyecto.Application.DTOs.ClienteDTO
@using Proyecto.Application.DTOs



<div id="detalleCliente">
    <h4>Reporte de Dueño del NFT</h4>
    <hr />
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.IdCliente)</th>
                <th>@Html.DisplayNameFor(model => model.Nombre)</th>
                <th>@Html.DisplayNameFor(model => model.Apellido1)</th>
                <th>@Html.DisplayNameFor(model => model.Apellido2)</th>
                <th>@Html.DisplayNameFor(model => model.Email)</th>
                <th>NFT</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Html.DisplayFor(model => model.IdCliente)</td>
                <td>@Html.DisplayFor(model => model.Nombre)</td>
                <td>@Html.DisplayFor(model => model.Apellido1)</td>
                <td>@Html.DisplayFor(model => model.Apellido2)</td>
                <td>@Html.DisplayFor(model => model.Email)</td>
                <td>
                    @{
                        var nftId = ((IEnumerable<NFTDTO>)ViewBag.nft).ToList();
                        var NFTDict = nftId.ToDictionary(c => c.IdNft, c => c.Imagen);
                    }
                    @{
                        //preguntamos si el diccionario lo tiene
                        if (NFTDict.ContainsKey(nftId.First().IdNft))
                        {
                            var imageBytes = NFTDict[nftId.First().IdNft];
                            var imageBase64 = Convert.ToBase64String(imageBytes);
                            <img src="data:image/png;base64,@imageBase64" alt="Imagen del NFT" width="200" height="200" />
                        }
                    }
                </td>
            </tr>
        </tbody>
    </table>
</div>